version: '3.8'
services:
  influencer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: influencer_db
      DB_DATABASE: microservices_influencer
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: always
    volumes:
      - .:/app
    ports:
      - 8019:8000
    depends_on:
      - influencer_db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    environment:
      DB_HOST: influencer_db
      DB_DATABASE: microservices_influencer
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - influencer_db

  influencer_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: microservices_influencer
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3021:3306

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - app
    ports:
      - 6379:6379
